#+TITLE: Rust digiKam ORM
This implements a rust ORM for querying the [[https://www.digikam.org/][digiKam]] database.

Currently this only supports querying the SQLite database not the MySQL version.

In addition this also has a program which leverages the ORM to set the wallpaper based on digiKam tags.

* Build
#+begin_src shell
cargo build
#+end_src

* digikam-wallpaper
This sets the wallpaper by filtering Image Metadata in the Digikam database. It can also get if the system is in ~Dark~ or ~Light~ mode and apply extra tags based on which mode the system is in.

** Usage
When run without arguments it will attempt to read from a configuration file and if that fails if will apply default values
Run ~digikam-wallpaper -h~ to view command line arguments.
** Configuration File
The default configuration directory depends on your system:
- Linux: XDG Directory Specification i.e: ~$HOME/.config/digikam-wallpaper/config.json~
  
To generate a configuration file with default values run:
#+begin_src shell
digikam-wallpaper --config-template
#+end_src

** Todo
- Filters
  + Time Based
    - Sunrise/Sunset
    - Season
    - Holidays
  + Current Weather Based
- Run as a deamon to dynamically change the wallpaper when filters are met

